### ISSUE TITLE
docker image on centos 7 using python2.7 instead of python3

### ISSUE THREAD

**Issue by rmunoz10** [scrapinghub/scrapyrt#110]
Hi
We have docker running on centos 7.
Install scrapyrt and a project for python3
Scrapyrt runs fine but using python2 causing it to fail
Below is a snippet of the logs:
Anything I'm missing?
Thanks

2020-07-24 14:35:00+0000 [-] Log opened.
2020-07-24 14:35:00+0000 [-] Site starting on 9080
2020-07-24 14:35:00+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f33bfa2e248>
2020-07-24 14:36:03+0000 [scrapyrt] Created request for spider example with url http://analyticalreporting.com and kwargs {}
2020-07-24 14:36:03+0000 [scrapyrt] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2145, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 890, in requestReceived

**Comment by boan-anbo** [comment]
> Hi
> We have docker running on centos 7.
> Install scrapyrt and a project for python3
> Scrapyrt runs fine but using python2 causing it to fail
> Below is a snippet of the logs:
> Anything I'm missing?
> Thanks
> 
> 2020-07-24 14:35:00+0000 [-] Log opened.
> 2020-07-24 14:35:00+0000 [-] Site starting on 9080
> 2020-07-24 14:35:00+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f33bfa2e248>
> 2020-07-24 14:36:03+0000 [scrapyrt] Created request for spider example with url http://analyticalreporting.com and kwargs {}
> 2020-07-24 14:36:03+0000 [scrapyrt] Unhandled Error
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2145, in allContentReceived
> req.requestReceived(command, path, version)
> File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 890, in requestReceived

don't pull directly from Docker hub, which is running python 2. use the updated Dockerfile in this repo to build your own image.

**Comment by pawelmhm** [comment]
We'll drop Python2 support with next release, so this will be more explicit.
