### ISSUE TITLE
SyntaxError: invalid syntax... msg += f' {str(e)}'^ after upgrading to latest Node.js

### ISSUE THREAD

**Issue by doverradio** [scrapinghub/scrapyrt#142]
```
/root/.pm2/logs/scrapyrt--p-5043--i-165.232.154-error.log last 15 lines:
68|bing:50 | Traceback (most recent call last):
68|bing:50 |   File "/usr/local/bin/scrapyrt", line 8, in <module>
68|bing:50 |     sys.exit(execute())
68|bing:50 |   File "/usr/local/lib/python2.7/dist-packages/scrapyrt/cmdline.py", line 91, in execute
68|bing:50 |     application = get_application(arguments)
68|bing:50 |   File "/usr/local/lib/python2.7/dist-packages/scrapyrt/cmdline.py", line 55, in get_application
68|bing:50 |     ServiceRoot = load_object(settings.SERVICE_ROOT)
68|bing:50 |   File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 46, in load_object
68|bing:50 |     mod = import_module(module)
68|bing:50 |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
68|bing:50 |     __import__(name)
68|bing:50 |   File "/usr/local/lib/python2.7/dist-packages/scrapyrt/resources.py", line 237
68|bing:50 |     msg += f' {str(e)}'
68|bing:50 |                       ^
68|bing:50 | SyntaxError: invalid syntax
```

I upgraded to Node.js 16 and all my pm2 logs showed error states.

What can I do to solve this?

Please let me know. 

Thanks!

**Comment by doverradio** [comment]
Solved this by reinstalling everything all over again in a new virtual environment.  After, things began to work again after it had issues locating the scrapy.conf file.
