### ISSUE TITLE
Scarpyrt error when runing with callback

### ISSUE THREAD

**Issue by oroszlorand** [scrapinghub/scrapyrt#151]
Hi, i'm runing scrapyrt, and i call carwl.json with spider_name, url, callback arguments, but i get an error:

ERROR:scrapy.utils.signal:Error caught on signal handler: <bound method CrawlManager.spider_idle of <scrapyrt.core.CrawlManager object at 0x7ff435d75f60>>
Traceback (most recent call last):
  File "/home/lorand/PycharmProjects/scrapy/venv/lib/python3.10/site-packages/scrapy/utils/signal.py", line 43, in send_catch_log
    response = robustApply(
  File "/home/lorand/PycharmProjects/scrapy/venv/lib/python3.10/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/lorand/PycharmProjects/scrapy/venv/lib/python3.10/site-packages/scrapyrt/core.py", line 181, in spider_idle
    spider.crawler.engine.crawl(self.request, spider)
TypeError: ExecutionEngine.crawl() takes 2 positional arguments but 3 were given
INFO:scrapy.core.engine:Closing spider (finished)

i just don't know what to do with the error.

**Comment by pawelmhm** [comment]
need to update to most recent scrapyrt version see here https://github.com/scrapinghub/scrapyrt/issues/148
