### ISSUE TITLE
twisted headers error

### ISSUE THREAD

**Issue by kotEustachy** [scrapinghub/scrapyrt#85]
scrapyrt invoke scrapy crawler and crawl normally but no response is returned after upating twisted to 19.2.0

https://github.com/crossbario/crossbar/issues/1557

Traceback (most recent call last):
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
	    status.deferred.callback(getattr(e, "value", None))
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/scrapyrt/resources.py", line 37, in finish_request
	    request.write(self.render_object(obj, request))
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/scrapyrt/resources.py", line 95, in render_object
	    request.setHeader('Content-Length', len(r))
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/web/http.py", line 1271, in setHeader
	    
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
	    else:
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/web/http_headers.py", line 220, in <listcomp>
	    else:
	  File "/home/crawler/easyitem_crawler_rest/venv/lib/python3.6/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
	    above, using just L{bytes} arguments to the methods of this class will
	builtins.AttributeError: 'int' object has no attribute 'splitlines'

**Comment by pawelmhm** [comment]
This seems to be fixed here #84
